# Generated by Django 6.1.1 on 2026-10-03 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def prepare_legacy_attempts(apps, schema_editor):
    Answer = apps.get_model('studentside', 'StudentAnswer')
    Attempt = apps.get_model('studentside', 'StudentExamAttempt')
    database = schema_editor.connection.alias
    duplicates = Answer.objects.using(database).values('student_exam_attempt_id', 'question_id').annotate(total=models.Count('id')).filter(total__gt=1)
    for group in duplicates.iterator():
        rows = Answer.objects.using(database).filter(student_exam_attempt_id=group['student_exam_attempt_id'], question_id=group['question_id']).order_by('-id')
        rows.exclude(pk=rows.first().pk).delete()
    for attempt in Attempt.objects.using(database).select_related('exam').iterator():
        attempt.started_at = attempt.proctoring_started_at
        attempt.expires_at = min(attempt.started_at + attempt.exam.timelimit, attempt.exam.deadline) if attempt.started_at else attempt.exam.deadline
        if not attempt.completed_at:
            attempt.monitoring_interrupted = True
            # A restarted server cannot safely recreate this existing pipeline.
            attempt.monitoring_started = True
        attempt.save(using=database, update_fields=['started_at', 'expires_at', 'monitoring_interrupted', 'monitoring_started'])


class Migration(migrations.Migration):

    dependencies = [
        ('studentside', '0004_studentexamattempt_prediction'),
        ('teacherside', '0004_question_correct_answer_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=32, unique=True)),
                ('camera_id', models.CharField(blank=True, max_length=256)),
                ('calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='monitoring_interrupted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='monitoring_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='writer_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamattempt',
            name='writer_token',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.RunPython(prepare_legacy_attempts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='studentanswer',
            constraint=models.UniqueConstraint(fields=('student_exam_attempt', 'question'), name='one_answer_per_question'),
        ),
        migrations.AddField(
            model_name='exampreparation',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherside.exam'),
        ),
        migrations.AddField(
            model_name='exampreparation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
