# Generated by Django 6.1.1 on 2026-10-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherside', '0003_exam_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_description',
            field=models.TextField(blank=True),
        ),
    ]
